"""Initial schema

Revision ID: e6508b3e12b1
Revises: 
Create Date: 2026-09-18 15:22:01.529704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6508b3e12b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hubs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('incident_version', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vehicles', sa.JSON(), nullable=False),
    sa.Column('transfers', sa.JSON(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('incremental_cost', sa.Float(), nullable=False),
    sa.Column('extra_distance', sa.Float(), nullable=False),
    sa.Column('sla_margin_minutes', sa.Float(), nullable=False),
    sa.Column('constraint_checks', sa.JSON(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('planned_route', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=False),
    sa.Column('max_volume', sa.Float(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('shift_start', sa.DateTime(), nullable=False),
    sa.Column('shift_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('shipments')
    op.drop_table('recovery_plans')
    op.drop_table('hubs')
    op.drop_table('events')
    # ### end Alembic commands ###
